#!/usr/bin/env python3
"""Capture streaming ETM instruction trace unattended via J-Trace + Ozone.

Generates a throwaway Ozone project (never touches a reference project
given with --jdebug), launches Ozone on a virtual display (xvfb-run),
drives the whole session over Ozone's automation TCP socket (UM08025 §6.7):
connect -> flash -> run for --duration-ms under streaming trace -> halt ->
export. Outputs in --out:
  code_profile.txt   hot functions (run/fetch counts) + code coverage
  itrace.csv         raw instruction history (only with --trace-csv)
  ozone_console.log, jlink.log, ozone_gui.log   session evidence

Requires firmware whose init enables the trace pins and clock, and the board
wired to a J-Trace.
Analyze results with etm_profile.py in this directory.
"""

import argparse
import os
import re
import shutil
import signal
import socket
import string
import subprocess
import sys
import tempfile
import time

# Throwaway Ozone project. SP/PC-from-vector-table hooks match the committed
# reference projects (Cortex-M generic). $$(InstallDir) -> literal $(InstallDir).
PROJECT_TEMPLATE = string.Template("""\
/* Auto-generated by etm_capture.py (etm-trace skill) - throwaway, do not commit. */
void OnProjectLoad (void) {
  Project.SetDevice ("$device");
  Project.SetHostIF ("USB", "$probe");
  Project.SetTargetIF ("$target_if");
  Project.SetTIFSpeed ("$tif_speed");
  Project.SetTraceSource ("Trace Pins");
  Project.SetTracePortWidth ($port_width);
$timing_line$core_clock_line$timestamps_line$hss_line$power_lines  Edit.SysVar (VAR_TRACE_MAX_INST_CNT, $max_inst);
  Edit.Preference (PREF_TIMESTAMP_FORMAT, TIMESTAMP_FORMAT_TIME);
  Project.AddSvdFile ("$$(InstallDir)/Config/Peripherals/ARMv7M.svd");
  Project.SetConsoleLogFile ("$outdir/ozone_console.log");
  Project.SetJLinkLogFile ("$outdir/jlink.log");
$os_plugin_line  File.Open ("$elf");
}
$jlink_script_hook

$reset_hook

$download_hook
$user_funcs""")

# Cortex-M generic SP/PC-from-vector-table init. A committed board reference
# overrides these verbatim (e.g. RT1176 apps in FlexSPI NOR need the ROM
# bootloader to do SP/PC init, plus a JTAG_nTRST pad fix).
DEFAULT_HOOK = """\
void %s (void) {
  unsigned int SP;
  unsigned int PC;
  unsigned int VectorTableAddr;
  VectorTableAddr = Elf.GetBaseAddr();
  if (VectorTableAddr == 0xFFFFFFFF) {
    Util.Log("etm_capture: failed to get program base");
  } else {
    SP = Target.ReadU32(VectorTableAddr);
    Target.SetReg("SP", SP);
    PC = Target.ReadU32(VectorTableAddr + 4);
    Target.SetReg("PC", PC);
  }
}"""

# Symbolic constants (TP_OP_*, EXPORT_*) only evaluate in project-script
# context, never over the automation socket - so these live in generated user
# functions invoked via Script.Exec (UM08025 SS6.7, SS7.9.9.1).
TRACEPOINT_FUNC = """\

void SetupTracepoints (void) {
%s}
"""

LINES_CSV_FUNC = """\

void ExportLinesCsv (void) {
  Export.CodeProfile ("%s", EXPORT_AS_CSV | EXPORT_CSV_LINES | EXPORT_FILE_PATHS, "");
}
"""

INSTS_CSV_FUNC = """\

void ExportInstsCsv (void) {
  Export.CodeProfile ("%s", EXPORT_AS_CSV | EXPORT_CSV_INSTS | EXPORT_FILE_PATHS, "");
}
"""


JLINK_SCRIPT_HOOK = """\

void BeforeTargetConnect (void) {
  Project.SetJLinkScript ("%s");
}
"""


def run_tool(env, name, args, what, **kw):
    """Run an external tool whose name `env` may override; a missing tool or a
    failed run is an error here, never an empty result to parse."""
    exe = os.environ.get(env) or name
    try:
        r = subprocess.run([exe, *args], capture_output=True, text=True, **kw)
    except OSError as e:
        sys.exit(f"error: cannot run {exe} ({what}): {e} - install it or set {env}=<path>")
    except subprocess.TimeoutExpired as e:
        sys.exit(f"error: {exe} hung ({what}): no answer in {e.timeout:g} s - "
                 "is the probe held, or the host's USB stuck enumerating a device?")
    if r.returncode != 0:
        sys.exit(f"error: {exe} failed ({what}, rc={r.returncode}): "
                 f"{(r.stderr or r.stdout).strip()[-300:]}")
    return r


FUNC_HEAD = re.compile(r"^\w[^;{}()]*\([^;{}()]*\)\s*\{", re.M)
SCRIPT_CALL = re.compile(r'(Project\.SetJLinkScript\s*\(\s*")([^"]*)(")')

# OnProjectLoad belongs to the template, so every statement of the reference's
# must be one it carries over or one it replaces on purpose: the probe comes from
# --probe, the program from --elf, the power rate from --power-hz; SVD files and
# SWO only feed views a headless trace-pin capture never opens.
QUOTED = r'"([^"]*)"'
CARRIED = {"Project.SetDevice": ("device", QUOTED),
           "Project.SetTargetIF": ("target_if", QUOTED),
           "Project.SetTIFSpeed": ("tif_speed", QUOTED),
           "Project.SetJLinkScript": ("jlink_script", QUOTED),
           "Project.SetTracePortWidth": ("port_width", r"(\d+)"),
           "Project.SetTraceTiming": ("timing", r"(-?\d+(?:\s*,\s*-?\d+){3})")}
REPLACED = {"Project.SetHostIF", "File.Open", "Project.AddSvdFile", "Project.SetSWO"}


def strip_comments(text):
    """String-aware: a '//' inside a quoted path is not a comment."""
    return re.sub(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/',
                  lambda m: m.group(0) if m.group(0)[0] == '"' else "", text, flags=re.S)


def project_load_settings(path, block):
    """The settings OnProjectLoad makes, from literal arguments only: a prefix
    match would read `1 << 2` as width 1."""
    found = {}
    body = block.split("{", 1)[1].rsplit("}", 1)[0]
    for stmt in (s.strip() for s in body.split(";")):
        m = re.fullmatch(r"(\w+\.\w+)\s*\((.*)\)", stmt, re.S)
        call, arg = (m.group(1), m.group(2).strip()) if m else (None, "")
        key = value = None
        if not stmt or call in REPLACED:
            continue
        if call in CARRIED:
            key, pat = CARRIED[call]
            value = re.fullmatch(pat, arg)
        elif call == "Edit.SysVar":
            value = re.fullmatch(r"VAR_TRACE_CORE_CLOCK\s*,\s*(\d+)", arg)
            key = "core_clock"
            if not value and arg.split(",")[0].strip() == "VAR_POWER_SAMPLING_SPEED":
                continue
        elif call == "Project.SetTraceSource" and arg == '"Trace Pins"':
            continue
        if not value:
            sys.exit(f"error: {path}: OnProjectLoad statement the capture would drop or "
                     f"cannot read as a literal: {' '.join(stmt.split())!r}")
        text = value.group(1)
        found.setdefault(key, set()).add(" ".join(text.split()) if key == "timing" else text)
    for key, values in found.items():
        if len(values) > 1:
            sys.exit(f"error: {path} sets {key} more than once, to different values: "
                     + ", ".join(sorted(values)))
    return {key: values.pop() for key, values in found.items()}


def resolve_jdebug(path):
    """Trace config inherited from a reference Ozone project (device, target
    interface, TIF speed, trace timing/width, core clock, user hooks, J-Link
    script). Anything in the file this cannot carry over is refused: a hook or
    a setting dropped silently changes how the target is brought up."""
    cfg = {"device": None, "target_if": None, "tif_speed": None, "timing": None,
           "port_width": None, "core_clock": None, "ref": path}
    if not os.path.isfile(path):
        sys.exit(f"error: reference project not found: {path}")
    text = strip_comments(open(path).read())
    # inherit every user function verbatim except OnProjectLoad, which the
    # template owns (e.g. STM32H5's AfterTargetConnect must clock the trace
    # CoreSight domain; RT1176 replaces the SP/PC reset/download hooks for
    # ROM-bootloader boot; Nordic hooks call a _SetupTarget helper that
    # must ride along or hook execution fails at runtime)
    extra, rest = [], text
    for m in re.finditer(r"^void (\w+)\s*\(void\)\s*\{.*?^\}", text,
                         re.M | re.S):
        name, block = m.group(1), m.group(0)
        rest = rest.replace(block, "", 1)
        if len(FUNC_HEAD.findall(block)) > 1:
            sys.exit(f"error: {path}: '{name}' does not end with a '}}' at column 0, "
                     f"so the function after it cannot be told apart - unsupported")
        if name != "BeforeTargetConnect" and name != "OnProjectLoad" and SCRIPT_CALL.search(block):
            sys.exit(f"error: {path}: Project.SetJLinkScript inside '{name}' - supported "
                     f"only in OnProjectLoad and BeforeTargetConnect")
        if name == "OnProjectLoad":
            cfg.update(project_load_settings(path, block))
        elif name == "BeforeTargetConnect":
            cfg["before_connect"] = block
        elif name == "AfterTargetReset":
            cfg["reset_hook"] = block
        elif name == "AfterTargetDownload":
            cfg["download_hook"] = block
        else:
            extra.append(block)
    left = rest.strip()
    if left:
        sys.exit(f"error: {path}: unsupported content outside 'void NAME (void) {{...}}' "
                 f"functions, it would be dropped: {left.splitlines()[0].strip()!r}")
    if extra:
        cfg["connect_hook"] = "\n\n".join(extra) + "\n"
    hook_scripts = set(m.group(2) for m in SCRIPT_CALL.finditer(cfg.get("before_connect", "")))
    if len(hook_scripts) > 1 or (hook_scripts and cfg.get("jlink_script")):
        sys.exit(f"error: {path} sets the J-Link script more than once - which call "
                 f"runs depends on Ozone, so the capture cannot reproduce it")
    if hook_scripts:
        cfg["jlink_script"] = hook_scripts.pop()
    # e.g. RT1176 must declare its off-ROM-table TPIU/funnel in a J-Link script;
    # $(ProjectDir) = the reference's own directory
    if cfg.get("jlink_script"):
        rel = cfg["jlink_script"].replace("$(ProjectDir)", ".")
        if "$(" in rel:
            sys.exit(f"error: {path}: cannot resolve the macro in J-Link script path "
                     f"{cfg['jlink_script']!r} (only $(ProjectDir) is known)")
        cfg["jlink_script"] = os.path.normpath(os.path.join(os.path.dirname(path), rel))
        # rewritten where it stands: a call the reference guards stays guarded
        if "before_connect" in cfg and SCRIPT_CALL.search(cfg["before_connect"]):
            cfg["before_connect"] = SCRIPT_CALL.sub(
                lambda m: m.group(1) + cfg["jlink_script"] + m.group(3), cfg["before_connect"])
            cfg["script_in_hook"] = True
    for key, call in (("device", "Project.SetDevice"), ("target_if", "Project.SetTargetIF"),
                      ("tif_speed", "Project.SetTIFSpeed"),
                      ("port_width", "Project.SetTracePortWidth")):
        if not cfg[key]:
            sys.exit(f"error: {path} has no {call} - not an Ozone project?")
    return cfg


def before_connect_hook(cfg, cli_script):
    """The one BeforeTargetConnect of the generated project: the reference's own
    statements, plus the J-Link script call with its path made absolute."""
    if cli_script and cfg.get("jlink_script"):
        sys.exit(f"error: --jlink-script conflicts with the reference project's own "
                 f"J-Link script {cfg['jlink_script']}")
    script = os.path.abspath(cli_script) if cli_script else cfg.get("jlink_script")
    block = cfg.get("before_connect")
    if not script or cfg.get("script_in_hook"):
        return "\n" + block + "\n" if block else ""
    if not block:
        return JLINK_SCRIPT_HOOK % script
    head, body = block.split("{", 1)
    return f'\n{head}{{\n  Project.SetJLinkScript ("{script}");{body}\n'


def trace_only_points(elf, syms_arg):
    """Tracepoint lines for --trace-only: start trace at each symbol's entry,
    stop at each return instruction inside it (pop ...pc / bx lr, via objdump).
    Hardware comparators are scarce (ETM-M7) - keep the symbol list short."""
    lines = ""
    nm = run_tool("ETM_NM", "arm-none-eabi-nm", ["-S", "--defined-only", elf],
                  "symbols for --trace-only").stdout
    for want in [s.strip() for s in syms_arg.split(",") if s.strip()]:
        m = re.search(rf"^([0-9a-f]+) ([0-9a-f]+) [TtWw] {re.escape(want)}$",
                      nm, re.M)
        if not m:
            sys.exit(f"error: --trace-only symbol '{want}' not in ELF")
        lo, sz = int(m.group(1), 16) & ~1, int(m.group(2), 16)
        lines += f'  Trace.SetPoint (TP_OP_START_TRACE, "{want}");\n'
        dis = run_tool("ETM_OBJDUMP", "arm-none-eabi-objdump",
                       ["-d", f"--start-address={lo:#x}", f"--stop-address={lo + sz:#x}", elf],
                       "return instructions for --trace-only").stdout
        exits = re.findall(
            r"^\s*([0-9a-f]+):.*?(?:(?:pop|ldmia[.\w]*\s+sp!,)[^\n]*\bpc\b|bx\s+lr)",
            dis, re.M | re.I)
        if not exits:
            sys.exit(f"error: no return instruction found in '{want}'")
        for addr in exits:
            lines += f'  Trace.SetPoint (TP_OP_STOP_TRACE, "0x{int(addr, 16):08X}");\n'
    return lines


SECTION_ROW = re.compile(r"^\s*\d+\s+(\S+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s", re.I)


def ram_code_sections(elf):
    """(name, address, size) of each code section startup copies elsewhere
    (VMA != LMA). Ozone analyses code from the program file's load image only:
    a trace through such code is 'not covered by trace cache' and an
    instruction-trace export that meets it comes out truncated."""
    dump = run_tool("ETM_OBJDUMP", "arm-none-eabi-objdump", ["-h", elf],
                    "section headers").stdout.splitlines()
    found = []
    for row, flags in zip(dump, dump[1:]):
        m = SECTION_ROW.match(row)
        if m and "CODE" in re.split(r"[,\s]+", flags):
            name, size, vma, lma = m.group(1), *(int(v, 16) for v in m.group(2, 3, 4))
            if vma != lma and size:
                found.append((name, vma, size))
    return found


RUN_MARK = "=== traced run:"


def unknown_code(session_log):
    """Addresses Ozone traced without an image of the code, within the traced
    run; the boot ROM before main shows up earlier and costs nothing."""
    run = session_log.partition(RUN_MARK)[2]
    return sorted(set(re.findall(r"Addr\. (0x[0-9A-Fa-f]+) was traced but is not covered", run)))


def resolve_probe(probe):
    """Ozone's SetHostIF needs a serial - with several probes connected a
    nickname makes it block on a selection dialog. JLinkExe DOES resolve
    nicknames, so borrow its banner to map nickname -> serial. The serial only
    ever lands in the throwaway project file, never in committed files."""
    if probe.isdigit():
        return probe
    r = run_tool("ETM_JLINK_EXE", "JLinkExe", ["-USB", probe, "-nogui", "1"],
                 "probe nickname to serial", input="qc\n", timeout=30)
    m = re.search(r"S/N:\s*(\d+)", r.stdout)
    if not m:
        sys.exit(f"error: cannot resolve probe nickname '{probe}' to a serial "
                 f"(JLinkExe -USB {probe} found no emulator)")
    return m.group(1)


def gen_project(cfg, args, outdir):
    timing = ""
    if args.trace_timing is not None:
        d = args.trace_timing
        timing = ("  Project.SetTraceTiming "
                  f"({d[0]}, {d[1]}, {d[2]}, {d[3]});\n")
    elif cfg["timing"]:
        timing = f"  Project.SetTraceTiming ({cfg['timing']});\n"
    core_clock = args.core_clock or cfg["core_clock"]
    clk_line = f"  Edit.SysVar (VAR_TRACE_CORE_CLOCK, {core_clock});\n" if core_clock else ""
    ts_line = ("  Edit.SysVar (VAR_TRACE_TIMESTAMPS_ENABLED, 0);\n"
               if args.no_timestamps else "")
    user_funcs = ""
    if cfg.get("connect_hook"):
        user_funcs += "\n" + cfg["connect_hook"]
    if args.trace_only:
        user_funcs += TRACEPOINT_FUNC % args.tracepoints
    if args.profile_lines_csv:
        user_funcs += LINES_CSV_FUNC % os.path.join(outdir, "profile_lines.csv")
    if args.profile_insts_csv:
        user_funcs += INSTS_CSV_FUNC % os.path.join(outdir, "profile_insts.csv")
    os_plugin = (f'  Project.SetOSPlugin ("{args.os_plugin}");\n'
                 if args.os_plugin else "")
    if args.attach:
        # attach to the running target: no download, no reset - trace a window
        # mid-run (firmware must match the ELF and have trace pins enabled)
        os_plugin += "  Debug.SetConnectMode (CM_ATTACH_HALT);\n"
    # HSS sampling rate belongs in OnProjectLoad (persistent) per UM08025 4.6.2;
    # setting it mid-session over the socket is rejected.
    hss = (f"  Edit.SysVar (VAR_HSS_SPEED, {args.sample_hz});\n"
           if args.sample else "")
    power = ("  Edit.SysVar (VAR_TARGET_POWER_ON, 1);\n"
             f"  Edit.SysVar (VAR_POWER_SAMPLING_SPEED, {args.power_hz});\n"
             if args.power else "")
    jls_hook = before_connect_hook(cfg, args.jlink_script)
    proj = os.path.join(outdir, "etm_capture.jdebug")
    if args.trace_width:
        cfg["port_width"] = args.trace_width
    with open(proj, "w") as f:
        f.write(PROJECT_TEMPLATE.substitute(
            device=cfg["device"], probe=args.probe_serial,
            target_if=cfg["target_if"], tif_speed=cfg["tif_speed"],
            port_width=cfg["port_width"], timing_line=timing, core_clock_line=clk_line,
            timestamps_line=ts_line, max_inst=args.max_inst, outdir=outdir,
            elf=os.path.abspath(args.elf), user_funcs=user_funcs,
            os_plugin_line=os_plugin, hss_line=hss, power_lines=power,
            jlink_script_hook=jls_hook,
            reset_hook=cfg.get("reset_hook", DEFAULT_HOOK % "AfterTargetReset"),
            download_hook=cfg.get("download_hook",
                                  DEFAULT_HOOK % "AfterTargetDownload")))
    return proj


LOOPBACK = ("0100007F", "0000000000000000FFFF00000100007F")
WILDCARD = ("00000000", "00000000000000000000000000000000")


def _tcp_rows():
    for table in ("/proc/net/tcp", "/proc/net/tcp6"):
        try:
            rows = open(table).read().splitlines()[1:]
        except OSError:
            continue
        for row in rows:
            f = row.split()
            (laddr, lport), (raddr, rport) = (x.rsplit(":", 1) for x in f[1:3])
            yield laddr, int(lport, 16), raddr, int(rport, 16), f[3], f[9]


def _holders(inodes):
    owners = {inode: set() for inode in inodes}
    for pid in filter(str.isdigit, os.listdir("/proc")):
        try:
            for fd in os.listdir(f"/proc/{pid}/fd"):
                link = os.readlink(f"/proc/{pid}/fd/{fd}")
                if link.startswith("socket:[") and link[8:-1] in owners:
                    owners[link[8:-1]].add(int(pid))
        except OSError:
            continue   # gone meanwhile, or not ours to read
    return owners


def listener_owner(port):
    """{inode: pids} of the sockets a connect to 127.0.0.1:port would reach (Linux
    /proc): the loopback listeners if there are any, else the wildcard ones. A
    listener on another address that only shares the port is not counted."""
    found = {inode: laddr in LOOPBACK for laddr, lport, _, _, state, inode in _tcp_rows()
             if state == "0A" and lport == port and laddr in LOOPBACK + WILDCARD}
    return _holders({i for i, specific in found.items() if specific} or set(found))


def peer_owner(port, client_port):
    """Pids holding the server end of our own connection: the listener can change
    hands between the ownership scan and the connect. Empty until the server
    accept()s - a connection still in the backlog has no owner yet."""
    inodes = {inode for laddr, lport, raddr, rport, state, inode in _tcp_rows()
              if state == "01" and inode != "0" and laddr in LOOPBACK and lport == port
              and raddr in LOOPBACK and rport == client_port}
    return set().union(*_holders(inodes).values()) if inodes else set()


def port_is_taken(port):
    with socket.socket() as probe:
        probe.settimeout(1)
        return probe.connect_ex(("127.0.0.1", port)) == 0


def fresh_outdir(out, device):
    """A run directory nothing was written to before: a reused one lets an older
    run's exports pass for this capture's."""
    if not out:
        return tempfile.mkdtemp(prefix=f"etm-{device}-")
    outdir = os.path.abspath(out)
    if os.path.lexists(outdir) and (not os.path.isdir(outdir) or os.listdir(outdir)):
        sys.exit(f"error: --out {outdir} already exists and is not an empty "
                 f"directory - give each capture its own directory")
    os.makedirs(outdir, exist_ok=True)
    return outdir


def requested_exports(args):
    names = ["code_profile.txt"]
    for wanted, name in ((args.profile_lines_csv, "profile_lines.csv"),
                         (args.profile_insts_csv, "profile_insts.csv"),
                         (args.trace_csv, "itrace.csv"),
                         (args.sample, "samples.csv"),
                         (args.power, "power.csv")):
        if wanted:
            names.append(name)
    return names


def missing_exports(outdir, names):
    return [n for n in names
            if not (os.path.isfile(os.path.join(outdir, n))
                    and os.path.getsize(os.path.join(outdir, n)) > 0)]


class Terminated(Exception):
    pass


STOP_SIGNALS = {signal.SIGTERM, signal.SIGINT}


def check_signals():
    """The session runs with its stop signals blocked, so none can cut through the
    launch or the teardown; every wait calls this instead."""
    pending = signal.sigpending() & STOP_SIGNALS
    if pending:
        raise Terminated(min(pending))


def _pgid(pid):
    try:
        return os.getpgid(pid)
    except OSError:
        return None


class OzoneSession:
    """Drive Ozone via its automation TCP socket (one connection at a time)."""

    def __init__(self, port, logf):
        self.port = port
        self.logf = logf
        self.sock = None

    def log(self, msg):
        line = f"[{time.strftime('%H:%M:%S')}] {msg}"
        print(line, flush=True)
        self.logf.write(line + "\n")
        self.logf.flush()

    def connect(self, timeout_s, proc):
        deadline = time.time() + timeout_s
        while time.time() < deadline:
            check_signals()
            if proc.poll() is not None:
                break
            # a live child does not make the socket ours: the listener must sit
            # in the process group this capture started
            owners = listener_owner(self.port)
            foreign = [sorted(pids) for pids in owners.values()
                       if not any(_pgid(pid) == proc.pid for pid in pids)]
            if foreign:
                raise RuntimeError(f"127.0.0.1:{self.port} is now held by a process outside "
                                   f"this capture (pids {foreign}) - refusing to drive it")
            if not owners:
                time.sleep(1)
                continue
            try:
                sock = socket.create_connection(("127.0.0.1", self.port), timeout=5)
            except OSError:
                time.sleep(1)
                continue
            accepted_by = set()
            for _ in range(50):
                accepted_by = peer_owner(self.port, sock.getsockname()[1])
                if accepted_by:
                    break
                time.sleep(0.1)
            if not any(_pgid(pid) == proc.pid for pid in accepted_by):
                sock.close()
                raise RuntimeError(f"the connection to 127.0.0.1:{self.port} was not accepted by "
                                   f"this capture's Ozone (pids {sorted(accepted_by) or 'none'}) "
                                   f"- refusing to drive it")
            self.sock = sock
            self.sock.settimeout(0.5)
            self.log(f"connected to Ozone automation socket :{self.port}")
            return
        if proc.poll() is not None:
            raise RuntimeError(f"Ozone exited (rc={proc.returncode}) before opening its "
                               f"automation socket (see ozone_gui.log)")
        raise TimeoutError(f"Ozone automation socket :{self.port} not reachable "
                           f"after {timeout_s}s (see ozone_gui.log)")

    def drain(self, wait_s=1.0):
        buf = b""
        end = time.time() + wait_s
        while time.time() < end:
            check_signals()
            try:
                chunk = self.sock.recv(65536)
                if not chunk:
                    break
                buf += chunk
                end = time.time() + 0.5  # keep reading while data flows
            except socket.timeout:
                pass
        text = buf.decode(errors="replace")
        for ln in text.splitlines():
            self.log(f"  ozone> {ln}")
        return text

    def send(self, cmd, wait_s=1.0):
        self.log(f"cmd: {cmd}")
        self.sock.sendall((cmd + "\n").encode())
        return self.drain(wait_s)

    def wait_echo(self, cmd, timeout_s):
        """Send cmd; wait until Ozone echoes its execution (echo comes after the
        command completed, e.g. a large Export). Returns all received text."""
        name = cmd.split("(")[0].strip()
        text = self.send(cmd, 1.0)
        deadline = time.time() + timeout_s
        while name + " (" not in text and name + "(" not in text:
            if time.time() > deadline:
                raise TimeoutError(f"no echo for '{name}' after {timeout_s}s")
            text += self.drain(1.0)
        return text

    def is_halted(self, timeout_s):
        """Poll Debug.IsHalted until it returns 1; parse the '// returns 0xN' echo."""
        deadline = time.time() + timeout_s
        while time.time() < deadline:
            text = self.send("Debug.IsHalted", 1.0)
            end2 = time.time() + 4.0
            while "Debug.IsHalted" not in text and time.time() < end2:
                text += self.drain(1.0)
            m = re.findall(r"Debug\.IsHalted\s*\(\);\s*//\s*returns\s*0x(\d+)", text)
            if m and m[-1] == "1":
                return True
            time.sleep(1)
        return False


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--jdebug", help="reference Ozone project (.jdebug) to inherit "
                   "device, TIF speed, trace timing/width, core clock, hooks and "
                   "J-Link script from; never opened by Ozone itself")
    p.add_argument("--device", help="J-Link device name when there is no reference "
                   "project (e.g. STM32F407VE for a SEGGER trace reference board); "
                   "needs --target-if, --tif-speed and --trace-width")
    p.add_argument("--target-if", choices=("SWD", "JTAG"),
                   help="debug interface of a --device target")
    p.add_argument("--tif-speed", help="debug interface speed of a --device target, "
                   "as Ozone writes it (e.g. '4 MHz')")
    p.add_argument("--jlink-script",
                   help="J-Link script file (.pex/.JLinkScript) for trace-pin "
                        "init when the firmware doesn't do it (SEGGER per-MCU "
                        "examples); wired into BeforeTargetConnect")
    p.add_argument("--power", action="store_true",
                   help="power the target from the probe and record a power "
                        "profile (power.csv); probe power is switched off after "
                        "the session. Target must be wired for probe power!")
    p.add_argument("--power-hz", type=int, default=10000,
                   help="power sampling frequency in Hz (default 10000)")
    p.add_argument("--elf", required=True, help="firmware ELF with trace init built in")
    p.add_argument("--duration-ms", type=int, default=10000, help="traced run time")
    p.add_argument("--out", help="output dir, new or empty (default: mkdtemp under /tmp)")
    p.add_argument("--port", type=int, default=19201,
                   help="automation socket port (19200 = interactive Ozone default; keep 19201)")
    p.add_argument("--probe", required=True,
                   help="J-Trace USB nickname or serial")
    p.add_argument("--trace-csv", action="store_true",
                   help="also export raw instruction history (itrace.csv, can be >100 MB)")
    p.add_argument("--max-inst", type=int, default=10000000,
                   help="VAR_TRACE_MAX_INST_CNT: instruction-trace window/export depth")
    p.add_argument("--core-clock", type=int,
                   help="CPU Hz for timestamp conversion (default: board reference value)")
    p.add_argument("--trace-timing",
                   help="trace sample delay in ps (-5000..5000, overrides the "
                        "board reference; sweep this when the stream dies with "
                        "unknown-packet errors). One value for all 4 pins, or "
                        "'d0,d1,d2,d3' to de-skew individual lines (boards can "
                        "have per-line RC delays, e.g. strap pulls on muxed pads)")
    p.add_argument("--trace-width", type=int, choices=(1, 2, 4),
                   help="trace port width: overrides the board reference (fewer "
                        "pins = tolerant of a single bad line, at reduced "
                        "bandwidth), required with --device")
    p.add_argument("--no-timestamps", action="store_true",
                   help="disable trace timestamps (less trace bandwidth -> fewer "
                        "overflows/decode errors; itrace.csv loses its time column)")
    p.add_argument("--trace-only",
                   help="comma-separated symbols: trace ONLY these functions via "
                        "hardware tracepoints (e.g. an ISR + SysTick_Handler for "
                        "calibration); needs few symbols (scarce comparators)")
    p.add_argument("--profile-lines-csv", action="store_true",
                   help="also export per-source-line profile/coverage counters "
                        "(profile_lines.csv)")
    p.add_argument("--profile-insts-csv", action="store_true",
                   help="also export per-instruction counters (profile_insts.csv, "
                        "enables branch-bias analysis in etm_profile.py)")
    p.add_argument("--attach", action="store_true",
                   help="attach to the RUNNING target instead of flash+reset: "
                        "capture a window mid-run (narrowing debug). The flashed "
                        "firmware must match --elf and have trace init built in")
    p.add_argument("--sample",
                   help="comma-separated C expressions to sample periodically "
                        "during the run (samples.csv, e.g. 'system_ticks')")
    p.add_argument("--sample-hz", type=int, default=1000,
                   help="data sampling frequency in Hz (default 1000)")
    p.add_argument("--os-plugin",
                   help="Ozone RTOS-awareness plugin for task/ISR-attributed "
                        "timeline, e.g. FreeRTOSPlugin_CM7 (from Plugins/OS of "
                        "the Ozone in use)")
    p.add_argument("--cortex-m-default-hooks", action="store_true",
                   help="fill a missing AfterTargetReset/AfterTargetDownload with the "
                        "generic Cortex-M one (SP/PC from the ELF's vector table); hooks "
                        "a reference project defines are always kept")
    args = p.parse_args()

    if sys.platform != "linux":
        sys.exit(f"error: unattended ETM capture is Linux-only (xvfb-run, /proc); "
                 f"this is {sys.platform}")
    if not args.probe.strip():
        p.error("--probe is empty: name the J-Trace (nickname or serial)")
    if bool(args.jdebug) == bool(args.device):
        sys.exit("error: need exactly one of --jdebug <reference.jdebug> or --device <name>")
    if args.max_inst > 10000000:
        # >10M yielded a silently EMPTY Export.Trace on Ozone V3.50
        print("warning: --max-inst clamped to 10000000 (larger values produce "
              "an empty instruction-trace export)", file=sys.stderr)
        args.max_inst = 10000000
    if not os.path.isfile(args.elf):
        sys.exit(f"error: ELF not found: {args.elf}")

    if args.trace_only:
        print("warning: --trace-only is EXPERIMENTAL - on some targets windows "
              "for low-rate handlers fail to record, and timestamps are invalid "
              "across trace gaps (instruction counts remain exact). For ISR "
              "timing prefer a full --trace-csv capture + etm_profile.py --isr.",
              file=sys.stderr)
    if args.device:
        unset = [f for f, v in (("--target-if", args.target_if), ("--tif-speed", args.tif_speed),
                                ("--trace-width", args.trace_width)) if not v]
        if unset:
            sys.exit(f"error: --device has no reference project to take "
                     f"{', '.join(unset)} from - pass them")
        cfg = {"device": args.device, "target_if": args.target_if, "tif_speed": args.tif_speed,
               "timing": None, "port_width": args.trace_width, "core_clock": None,
               "ref": "--device"}
    else:
        if args.target_if or args.tif_speed:
            sys.exit("error: --target-if/--tif-speed come from the reference project "
                     "with --jdebug; edit the reference instead")
        cfg = resolve_jdebug(os.path.abspath(args.jdebug))
    no_hook = [call for hook, call in (("reset_hook", "AfterTargetReset"),
                                       ("download_hook", "AfterTargetDownload"))
               if hook not in cfg]
    # an attach neither resets nor downloads: no hook of either kind ever runs
    if no_hook and not args.attach and not args.cortex_m_default_hooks:
        sys.exit(f"error: no {' / '.join(no_hook)} from {cfg['ref']} - pass "
                 f"--cortex-m-default-hooks if this target boots with SP/PC taken from "
                 f"the ELF's vector table, or give the reference its own hook")
    if port_is_taken(args.port):
        sys.exit(f"error: something already listens on 127.0.0.1:{args.port} - the session "
                 f"would drive that Ozone, not its own; close it or pass another --port")
    if not shutil.which("xvfb-run"):
        # never the caller's DISPLAY: Ozone would open there and take the keyboard
        sys.exit("error: xvfb-run not found - install xvfb; the capture only runs "
                 "Ozone on a virtual display")
    ozone_bin = os.environ.get("ETM_OZONE") or shutil.which("ozone") or shutil.which("Ozone")
    if not (ozone_bin and os.path.isfile(ozone_bin)):
        sys.exit(f"error: Ozone not found ({ozone_bin or 'ozone/Ozone not on PATH'}) - "
                 f"install SEGGER Ozone or set ETM_OZONE=<path>")
    if args.os_plugin:
        # the Ozone that will run, not any install that happens to have the plugin
        plugins = os.path.join(os.path.dirname(os.path.realpath(ozone_bin)), "Plugins", "OS")
        if not os.path.isfile(os.path.join(plugins, f"{args.os_plugin}.js")):
            sys.exit(f"error: RTOS plugin '{args.os_plugin}' not in {plugins} "
                     f"(e.g. FreeRTOSPlugin_CM7)")
    # everything that can refuse runs before the output directory exists
    if args.trace_timing is not None:
        try:
            d = [int(v) for v in args.trace_timing.split(",")]
        except ValueError:
            d = []
        if len(d) not in (1, 4) or not all(-5000 <= v <= 5000 for v in d):
            sys.exit("error: --trace-timing takes one value or d0,d1,d2,d3, each "
                     "-5000..5000 ps")
        args.trace_timing = d * 4 if len(d) == 1 else d
    args.tracepoints = (trace_only_points(os.path.abspath(args.elf), args.trace_only)
                        if args.trace_only else "")
    ram_code = ram_code_sections(os.path.abspath(args.elf))
    args.probe_serial = resolve_probe(args.probe)
    outdir = fresh_outdir(args.out, cfg["device"])
    proj = gen_project(cfg, args, outdir)

    cmd = ["xvfb-run", "-a", ozone_bin, "-project", proj, "-port", str(args.port)]

    gui_log = open(os.path.join(outdir, "ozone_gui.log"), "w")
    ses_logf = open(os.path.join(outdir, "session.log"), "w")
    ses = OzoneSession(args.port, ses_logf)
    ses.log(f"device={cfg['device']} ref={cfg['ref']}")
    ses.log(f"elf={args.elf}")
    ses.log(f"out={outdir}")
    def teardown(proc):
        if proc:
            # the group, not the child: xvfb-run can be gone while its Ozone lives on
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            proc.wait()
        if args.power:
            # guarantee probe power is off, whatever happened above
            exe = os.environ.get("ETM_JLINK_EXE") or "JLinkExe"
            try:
                r = subprocess.run([exe, "-USB", args.probe, "-nogui", "1"],
                                   input="power off\nqc\n", capture_output=True,
                                   text=True, timeout=30)
                result = "issued" if r.returncode == 0 else (
                    f"FAILED rc={r.returncode}: {(r.stderr or r.stdout).strip()[-300:]}")
            except (OSError, subprocess.TimeoutExpired) as e:
                result = f"FAILED ({e})"
            ses.log(f"probe power off {result}")
            if result != "issued":
                return f"probe power may still be ON: power off {result}"

    def pause(seconds):
        end = time.time() + seconds
        while time.time() < end:
            check_signals()
            time.sleep(min(0.5, max(0, end - time.time())))

    # blocked, not handled: a handler could fire between Popen and recording the
    # child, or inside the teardown; check_signals() honours them at every wait
    signal.pthread_sigmask(signal.SIG_BLOCK, STOP_SIGNALS)
    profile_out = os.path.join(outdir, "code_profile.txt")
    itrace_out = os.path.join(outdir, "itrace.csv")
    failure = stopped = proc = None
    try:
        proc = subprocess.Popen(
            cmd, stdout=gui_log, stderr=gui_log, start_new_session=True,
            preexec_fn=lambda: signal.pthread_sigmask(signal.SIG_UNBLOCK, STOP_SIGNALS))
        ses.connect(20, proc)
        ses.drain(3)  # version banner
        ses.send("Debug.Start", 5)
        if not ses.is_halted(90):
            raise TimeoutError("Debug.Start did not reach the startup completion "
                               "point (connect/flash failed? see jlink.log)")
        ses.log("startup complete (halted at main)")
        for name, addr, size in ram_code:  # copied by now, so target memory has it
            ses.wait_echo(f"Debug.ReadIntoInstCache (0x{addr:08X}, {size})", 30)
        if args.trace_only:
            ses.wait_echo('Script.Exec ("SetupTracepoints")', 15)
        ses.send('Window.Show ("Code Profile")', 2)
        if args.trace_csv:
            ses.send('Window.Show ("Instruction Trace")', 2)
        if args.sample:
            ses.send('Window.Show ("Data Sampling")', 2)
            for expr in args.sample.split(","):
                ses.send(f'Window.Add ("Data Sampling", "{expr.strip()}")', 2)
        ses.send("Coverage.ExcludeNOPs()", 2)

        ses.log(f"{RUN_MARK} {args.duration_ms} ms ===")
        ses.send("Debug.Continue", 1)
        pause(args.duration_ms / 1000.0)
        ses.send("Debug.Halt", 3)
        if not ses.is_halted(30):
            raise TimeoutError("target did not halt")
        ses.send("Window.WaitForUpdateComplete(120000)", 5)

        ses.wait_echo(f'Export.CodeProfile ("{profile_out}", 0, "")', 60)
        if args.profile_lines_csv:
            ses.wait_echo('Script.Exec ("ExportLinesCsv")', 60)
        if args.profile_insts_csv:
            ses.wait_echo('Script.Exec ("ExportInstsCsv")', 120)
        if args.trace_csv:
            ses.wait_echo(f'Export.Trace ("{itrace_out}", 0)', 300)
        if args.sample:
            ses.wait_echo(f'Export.DataGraphs ("{outdir}/samples.csv")', 60)
        if args.power:
            ses.wait_echo(f'Export.PowerGraphs ("{outdir}/power.csv")', 60)
        ses.send("Debug.Stop", 5)
        ses.send("File.Exit", 2)
        for _ in range(15):
            if proc.poll() is not None:
                break
            pause(1)
    except Terminated as t:
        stopped = t.args[0]
    except (TimeoutError, RuntimeError, OSError) as e:
        failure = str(e)
    finally:
        power_failure = teardown(proc)
    # one that arrived during the teardown is still pending: it must not turn
    # into "capture OK"
    stopped = stopped or min(signal.sigpending() & STOP_SIGNALS, default=None)
    if stopped:
        sys.exit(128 + stopped)

    failure = "; ".join(f for f in (failure, power_failure) if f)
    if failure:
        sys.exit(f"error: {failure} - evidence in {outdir}")
    missing = missing_exports(outdir, requested_exports(args))
    if missing:
        sys.exit(f"error: capture ran but {', '.join(missing)} missing/empty in "
                 f"{outdir} - check session.log and ozone_console.log there")
    if "Code Profile Report" not in open(profile_out, errors="replace").read(200):
        sys.exit(f"error: {profile_out} is not an Ozone code-profile report")
    session = open(os.path.join(outdir, "session.log"), errors="replace").read()
    if "Trace collection stopped!" in session:
        sys.exit("error: trace stream died mid-run (unknown trace data packet) - "
                 "the profile only covers up to that point. Retry with "
                 "--no-timestamps, or reduce the core clock (see SKILL.md).")
    unknown = unknown_code(session)
    if args.trace_csv and unknown:
        sys.exit(f"error: itrace.csv is truncated - the traced run executed code "
                 f"Ozone has no image of (at {', '.join(unknown)}: ROM, or code "
                 f"built at run time), and its export stops there. Evidence in {outdir}")
    prof = open(profile_out, errors="replace").read()
    m = re.search(r"^\s*Total\s*\|[\d ]*\|\s*([\d ]+)$", prof, re.M)
    if not m or int(m.group(1).replace(" ", "") or 0) == 0:
        sys.exit("error: session completed but NO trace data was collected "
                 "(profile totals are zero) - trace signal not reaching the "
                 "probe: check wiring/connector, trace pinmux, sample timing.")
    print(f"\ncapture OK: {outdir}")
    if unknown:
        print(f"  warning: the run executed code Ozone has no image of (at "
              f"{', '.join(unknown)}); its fetches are missing from the profile")
    print(f"  code_profile.txt  ({os.path.getsize(profile_out)} bytes)")
    if args.trace_csv:
        print(f"  itrace.csv        ({os.path.getsize(itrace_out)} bytes)")
    print(f"analyze: python3 {os.path.dirname(os.path.abspath(__file__))}"
          f"/etm_profile.py {outdir} --elf {args.elf}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
